### ISSUE TITLE
which version can compiled vlc-2.2.0-rc.2.32-2013

### ISSUE THREAD

**Issue by GodZza** [sunqueen/vlc-2.2.0-rc2.32-2013#1]
When i used (VS Express 2013 for Windows Desktop) to compile this project, there many errors occur cause compile fail. My guess is using C99 feature cause the error to occur in the project, and which version for VS2013 does to compile it.
VS2013 Ultimate
VS2013 Premium
VS2013 Professional
VS2013 Test Professional
VS2013 Team Foundation Server
VS2013 Express

thanks.

**Comment by sunqueen** [comment]
If you install VS2013, please upgrad 2 or upper version.
VS2013 original version has not fully support C99.

**Comment by GodZza** [comment]
i installed the VS2013 Professional version, and it can not compile the project, but when i download and install http://download.microsoft.com/download/9/4/3/9430B009-5E55-4D48-ADA6-CBC1E025573E/VS2013.4.exe  the VS2013 Professional version can compile it! 
thank you!
